# This YAML file is to be used with btk_input to simulate objects with
# BlendingTooKit and perform detection/deblending/measurements.
# Usage:
#    python3 ../btk_input.py --configfile ../input/example-config.yaml

# Modify the following values; specify directory locations and name of your function.
# If value are set to None, then the default btk parameters are used.

user_input:
    # Enter location to load dataset from (relative to where you open the yaml file)
    data_dir: ../data
    # Enter location where btk test output should be saved
    output_dir: example-output
    # Enter file name containing user function to perform detection/deblending/measurement
    utils_filename: None  # If None use btk/utils.py
    output_name: trial  # btk output will be saved in a directory with this name inside output_dir
    # Enter name of functions to perform detection/deblending/measurement.
    utils_input:
        measure_function: SEP_params
        metrics_function: None


# Below are the parameter values specifying 3 kinds of simulations.
# Do not change parameters below!!
---
simulation: two_gal
config:
    catalog: OneDegSq.fits
    max_number: 2
    batch_size: 8
    stamp_size: 25.6
    survey_name: "LSST"
    add_noise: True
    bands:
        - 'u'
        - 'g'
        - 'r'
        - 'i'
        - 'z'
        - 'y'
    min_snr: 0.05
    seed: 199
    add: None  # Additional arguments for btk.config.Simulation_params
    selection_function: basic_selection_function
    sampling_function: basic_sampling_function
    observe_function: None
    test_size: 20

---
simulation: multi_gal
config:
    catalog: OneDegSq.fits
    max_number: 10
    batch_size: 8
    stamp_size: 25.6
    survey_name: "LSST"
    add_noise: True
    bands:
        - 'u'
        - 'g'
        - 'r'
        - 'i'
        - 'z'
        - 'y'
    min_snr: 0.05
    seed: 199
    add: None  # Additional arguments for btk.config.Simulation_params
    selection_function: basic_selection_function
    sampling_function: basic_sampling_function
    observe_function: None
    test_size: 20

---

simulation: group
config:
    catalog: OneDegSq.fits
    max_number: 6
    batch_size: 8
    stamp_size: 25.6
    survey_name: "LSST"
    add_noise: True
    bands:
        - 'u'
        - 'g'
        - 'r'
        - 'i'
        - 'z'
        - 'y'
    min_snr: 0.05
    seed: 199
    add:
        # wld processed catalog with groups: relative to where you open the yaml file
        wld_catalog_name: 'data/test_group_catalog.fits'
    selection_function: None
    sampling_function: group_sampling_function
    observe_function: None
    test_size: 20

