_target_: btk.sampling_functions.GroupSampling
max_number: ${max_number}
stamp_size: ${stamp_size}
maxshift: ${max_shift}
wld_catalog_name: ${paths.data}/sample_group_catalog.fits
seed: ${seed}
shift: Null
