---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: trailing-whitespace
        exclude: ^.*fits
        args:
          - --markdown-linebreak-ext=md
      - id: check-added-large-files
        args:
          - "--maxkb=5000"
      - id: check-merge-conflict
      - id: end-of-file-fixer
        exclude: ^.*fits
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
        language_version: python3
        args:
          - "--line-length=100"
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v2.4.0
    hooks:
      - id: reorder-python-imports
  - repo: https://github.com/pycqa/flake8
    rev: 3.8.4
    hooks:
      - id: flake8
        args: # arguments to configure flake8
          # making isort line length compatible with black
          - "--max-line-length=100"
          - "--max-complexity=18"
          - "--ignore=E203, W503"
          - "--exclude=btk/__init__.py"
  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.0.0 # pick a git hash / tag to point to
    hooks:
      - id: pydocstyle
        args:
          - --config=.pydocstyle.ini
        exclude: |
          (?x)(
              ^docs/source/conf.py|
              ^conftest.py|
              ^tests/
          )
