language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"

# command to install dependencies
install:
  - apt-get install libfftw3-dev
  - pip install -r requirements.txt
  - pip install .
  - git clone https://github.com/LSSTDESC/WeakLensingDeblending
  - cd WeakLensingDeblending
  - git checkout no_analysis
  - python setup.py install




# command to run tests
script:
  - pytest
