# @package _group_
name: "CatsimGenerator"
kwargs:
  batch_size: 8
  stamp_size: 24
  meas_bands:
    - i
  cpus: ${cpus}
  verbose: ${verbose}
  add_noise: True
  shifts: Null
  indexes: Null
  channels_last: False
  save_path: ${save_path}
