defaults:
  - sampling: default
  - draw_blend: catsim

catalog:
  name: CatsimCatalog
  catalog_files: ${paths.data}/sample_input_catalog.fits

save_path: Null

cpus: 1

verbose: False

surveys:
  - name: Rubin
    filters:
      - i

measure:
  measure_functions:
    - basic
  kwargs:
    verbose: ${verbose}
    cpus: ${cpus}
    measure_kwargs: Null
    save_path: ${save_path}

metrics:
  kwargs:
    use_metrics:
      - detection
    meas_band_num: 0
    noise_threshold_factor: 3
    target_meas: Null
    save_path: ${save_path}

paths:
  root: ${env:BTK_HOME}
  data: ${paths.root}/data
