name: documentation

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  docs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
    - name: Checkout github repo
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}


    - name: install sphinx
      run: pip install sphinx mock sphinx_rtd_theme


    - name: run sphinx action
      uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "./docs"
