name: docs

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
      - name: Checkout github repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Create environment variables
        run: echo "BTK_HOME=$GITHUB_WORKSPACE" >> $GITHUB_ENV

      - name: Install Poetry
        run: |
          pip install --upgrade pip
          pip install poetry

      - name: Poetry cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/pypoetry
          key: ${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('./poetry.lock') }}

      # galsim needs this.
      - name: Instal FFTW + Eigen
        run: |
          sudo apt-get install libfftw3-dev

      - name: Install poetry dependencies
        run: |
          poetry run pip install Cython
          poetry install --extras "galsim-hub"

      - name: build docs
        shell: bash -l {0}
        run: |
          cd docs
          poetry run make html
          cd build/html
          touch .nojekyll

      - name: Commit documentation changes
        run: |
          git clone https://github.com/LSSTDESC/BlendingToolKit.git --branch gh-pages --single-branch gh-pages
          cp -r docs/build/html/* gh-pages/docs/
          cd gh-pages/docs
          touch .nojekyll
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update documentation" -a || true

      # The above command will fail if no changes were present, so we ignore that.
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: gh-pages
          directory: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
