name: docs

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
      - name: Checkout github repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install miniconda and environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          activate-environment: btk_py37
          python-version: ${{ matrix.python-version }}

      - name: Install conda dependencies
        shell: bash -l {0} # setup and activate conda environment.
        run: |
          conda install fftw
          conda install -c conda-forge eigen
          conda install -c conda-forge galsim
          conda install tensorflow==1.15
          conda install -c conda-forge poetry

      - name: Install poetry dependencies
        shell: bash -l {0}
        run: |
          poetry install --extras "galsim-hub"

      - name: build docs
        shell: bash -l {0}
        run: |
          cd docs
          poetry run make html
          cd build/html
          touch .nojekyll

      - name: Commit documentation changes
        run: |
          git clone https://github.com/LSSTDESC/BlendingToolKit.git --branch gh-pages --single-branch gh-pages
          cp -r docs/build/html/* gh-pages/docs/
          cd gh-pages/docs
          touch .nojekyll
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update documentation" -a || true

      # The above command will fail if no changes were present, so we ignore that.
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: gh-pages
          directory: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
