# This workflow will install Python dependencies, lint with Python 3.9
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: lint

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
      - name: Checkout github repo
        uses: actions/checkout@v2

      - name: Install poetry
        run: pipx install poetry

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
          cache: "poetry"

      # galsim needs this.
      - name: Instal FFTW
        run: |
          sudo apt-get install libfftw3-dev

      - name: Install poetry dependencies
        run: |
          poetry install

      - name: Run pre-commit checks
        run: |
          poetry run pre-commit install
          poetry run pre-commit run --all-files
