name: lint

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
      - name: Checkout github repo
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      # galsim needs this.
      - name: Install FFTW
        run: |
          sudo apt-get install libfftw3-dev

      - name: pip upgrade
        run: |
          pip install --upgrade pip
          pip install wheel setuptools pip --upgrade

      - name: Install Scarlet
        run: |
          pip install "pybind11[global]" pybind11
          pip install numpy scipy astropy
          pip install proxmin peigen autograd
          git clone https://github.com/pmelchior/scarlet.git; cd scarlet; pip install .

      - name: Install Dependencies
        run: |
          pip install -e .
          pip install -e ".[dev]"

      - name: Run pre-commit
        run: |
          pre-commit install
          pre-commit run --all-files

      - name: Run Ruff
        run: ruff check --output-format=github btk/ tests/
