# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
      - name: Checkout github repo
        uses: actions/checkout@v2
        with:
          lfs: true
          fetch-depth: 0

      - name: Install miniconda and environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          activate-environment: btk_py37
          python-version: ${{ matrix.python-version }}

      - name: Install conda dependencies
        shell: bash -l {0} # setup and activate conda environment.
        run: |
          conda install fftw 
          conda install -c conda-forge eigen
          conda install -c conda-forge galsim
          conda install tensorflow==1.15
          conda install -c conda-forge poetry

      - name: Install poetry dependencies
        shell: bash -l {0}
        run: |
          poetry install --extras "galsim-hub"

      - name: Run pre-commit checks
        uses: pre-commit/action@v2.0.0
