# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: lint

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8]

    steps:
      - name: Checkout github repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Create environment variables
        run: echo "BTK_HOME=$GITHUB_WORKSPACE" >> $GITHUB_ENV

      - name: Install Poetry
        run: |
          pip install --upgrade pip
          pip install poetry==1.1.11

      - name: Poetry cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/pypoetry
          key: ${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('./poetry.lock') }}

      # galsim needs this.
      - name: Instal FFTW + Eigen
        run: |
          sudo apt-get install libfftw3-dev

      - name: Install poetry dependencies
        run: |
          poetry run pip install Cython
          poetry install

      - name: Run pre-commit checks
        run: |
          poetry run pre-commit install
          poetry run pre-commit run --all-files
