name: pytest

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: "Setup Python, Poetry and Dependencies"
        uses: dsoftwareinc/setup-python-poetry-action@v1
        with:
          python-version: ${{ matrix.python-version }}
          poetry-version: 2.0.0

      # galsim needs this.
      - name: Install FFTW
        run: |
          sudo apt-get install libfftw3-dev

      - name: Install poetry dependencies
        run: |
          poetry install --with scarlet

      - name: Install Scarlet
        run: |
          poetry run pip install "pybind11[global]" peigen pybind11
          git clone https://github.com/pmelchior/scarlet.git; cd scarlet; poetry run python setup.py install

      - name: Run Tests
        run: |
          poetry run pytest --cov=./btk --cov-report=xml --durations=0

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: unittests
          env_vars: OS,PYTHON
          name: codecov-umbrella
          fail_ci_if_error: true
