# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: pytest

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
      - name: Checkout github repo (+ download lfs dependencies)
        uses: actions/checkout@v2
        with:
          lfs: true
          fetch-depth: 0

      - name: Install miniconda and environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python-version }}
          auto-activate-base: true

      - name: Install conda dependencies
        run: |
          conda activate base
          which python
          python --version
          conda install fftw 
          conda install -c conda-forge eigen
          conda install -c conda-forge galsim
          conda install tensorflow==1.15
          conda install -c conda-forge poetry

      - name: Install poetry dependencies
        run: |
          poetry install --extras "galsim-hub"

      - name: Run Tests
        run: |
          poetry run pytest --cov=./btk --cov-report=xml --durations=0

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: unittests
          env_vars: OS,PYTHON
          name: codecov-umbrella
          fail_ci_if_error: true
