name: pytest

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8]

    steps:
      - name: Checkout github repo (+ download lfs dependencies)
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        run: |
          pip install --upgrade pip
          pip install poetry==1.1.10

      - name: Create environment variables
        run: echo "BTK_HOME=$GITHUB_WORKSPACE" >> $GITHUB_ENV

      - name: Poetry cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/pypoetry
          key: ${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('./poetry.lock') }}

      # galsim needs this.
      - name: Instal FFTW
        run: |
          sudo apt-get install libfftw3-dev

      - name: Install poetry dependencies
        run: |
          poetry run pip install Cython
          poetry install --extras "galsim-hub scarlet"
          poetry run pip install git+https://github.com/pmelchior/scarlet

      - name: Run Tests
        run: |
          poetry run pytest --cov=./btk --cov-report=xml --durations=0

      - name: Run notebooks
        run: |
          poetry run pytest --nbval notebooks --sanitize-with tests/sanitize.cfg --ignore "notebooks/01b-scarlet-measure.ipynb"

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: unittests
          env_vars: OS,PYTHON
          name: codecov-umbrella
          fail_ci_if_error: true
